<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="moduleDsl" nsURI="http://www.xtext.org/ModuleDsl" nsPrefix="moduleDsl">
  <eClassifiers xsi:type="ecore:EClass" name="LANGUAGE">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" upperBound="-1"
        eType="#//MODULE_DECL" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MODULE_DECL">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="critdecl" eType="#//CRITERION_DECL"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataseldecl" eType="#//DATASEL_DECL"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" upperBound="-1"
        eType="#//VAR_CST" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instr" upperBound="-1"
        eType="#//INSTRUCTION" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CRITERION_DECL">
    <eStructuralFeatures xsi:type="ecore:EReference" name="crit" eType="#//CRITERION"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//END" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DATASEL_DECL">
    <eStructuralFeatures xsi:type="ecore:EReference" name="data1" eType="#//DATASEL"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data2" eType="#//DATASEL"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//END" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="END">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CRITERION">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="crit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DATASEL">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VAR_CST">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TYPE" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//END" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VAR" eSuperTypes="#//VAR_CST">
    <eStructuralFeatures xsi:type="ecore:EReference" name="flow" eType="#//Flow" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="range" eType="#//RANGE"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Flow">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flow" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CST" eSuperTypes="#//VAR_CST">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flow" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Literal"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TYPE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RANGE"/>
  <eClassifiers xsi:type="ecore:EClass" name="INTERVAL" eSuperTypes="#//RANGE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lsqbr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="min" eType="#//Literal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="max" eType="#//Literal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rsqbr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LSET" eSuperTypes="#//RANGE">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//Literal" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal"/>
  <eClassifiers xsi:type="ecore:EClass" name="INSTRUCTION"/>
  <eClassifiers xsi:type="ecore:EClass" name="IF_INSTR" eSuperTypes="#//INSTRUCTION">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condInstr" eType="#//EXPRESSION"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifst" eType="#//INSTRUCTION"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elst" eType="#//INSTRUCTION"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LOOP_INSTR" eSuperTypes="#//INSTRUCTION">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ERROR_INSTR" eSuperTypes="#//INSTRUCTION"/>
  <eClassifiers xsi:type="ecore:EClass" name="NULL_INSTR" eSuperTypes="#//INSTRUCTION"/>
  <eClassifiers xsi:type="ecore:EClass" name="ASSIGN_INSTR" eSuperTypes="#//INSTRUCTION">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sa" upperBound="-1" eType="#//SINGLE_ASSIGN"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//END" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SINGLE_ASSIGN">
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" eType="#//VAR_CST"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" eType="#//EXPRESSION"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EXPRESSION"/>
  <eClassifiers xsi:type="ecore:EClass" name="intLITERAL" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="realLITERAL" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="boolLITERAL" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="strLITERAL" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="enumLITERAL" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="bitLITERAL" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="hexLITERAL" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="identLITERAL" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="unknowLITERAL" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ERROR_ASSIGN" eSuperTypes="#//ERROR_INSTR">
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//END" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NULL_ASSIGN" eSuperTypes="#//NULL_INSTR">
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//END" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OR" eSuperTypes="#//EXPRESSION">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//EXPRESSION"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//EXPRESSION"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AND" eSuperTypes="#//EXPRESSION">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//EXPRESSION"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//EXPRESSION"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EQUAL_DIFF" eSuperTypes="#//EXPRESSION">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//EXPRESSION"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//EXPRESSION"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="COMPARISON" eSuperTypes="#//EXPRESSION">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//EXPRESSION"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//EXPRESSION"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Plus" eSuperTypes="#//EXPRESSION">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//EXPRESSION"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//EXPRESSION"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sub" eSuperTypes="#//EXPRESSION">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//EXPRESSION"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//EXPRESSION"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Multi" eSuperTypes="#//EXPRESSION">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//EXPRESSION"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//EXPRESSION"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Div" eSuperTypes="#//EXPRESSION">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//EXPRESSION"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//EXPRESSION"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="strREDUCTION" eSuperTypes="#//EXPRESSION">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//EXPRESSION"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pos" eType="#//EXPRESSION"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NOT" eSuperTypes="#//EXPRESSION">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" eType="#//EXPRESSION"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="intConstant" eSuperTypes="#//EXPRESSION">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="realConstant" eSuperTypes="#//EXPRESSION">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="strConstant" eSuperTypes="#//EXPRESSION">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="enumConstant" eSuperTypes="#//EXPRESSION">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="boolConstant" eSuperTypes="#//EXPRESSION">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VarExpRef" eSuperTypes="#//EXPRESSION">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vref" eType="#//VAR_CST"/>
  </eClassifiers>
</ecore:EPackage>
