/*
 * generated by Xtext
 */
package org.xtext.ui.contentassist

import org.xtext.ui.contentassist.AbstractModuleDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ModuleDslProposalProvider extends AbstractModuleDslProposalProvider {
}
