/*
* generated by Xtext
*/
package org.xtext.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.services.ModuleDslGrammarAccess;

public class ModuleDslParser extends AbstractContentAssistParser {
	
	@Inject
	private ModuleDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.ui.contentassist.antlr.internal.InternalModuleDslParser createParser() {
		org.xtext.ui.contentassist.antlr.internal.InternalModuleDslParser result = new org.xtext.ui.contentassist.antlr.internal.InternalModuleDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getCRITERIONAccess().getCritAlternatives_0(), "rule__CRITERION__CritAlternatives_0");
					put(grammarAccess.getDATASELAccess().getSelAlternatives_0(), "rule__DATASEL__SelAlternatives_0");
					put(grammarAccess.getVAR_CSTAccess().getAlternatives(), "rule__VAR_CST__Alternatives");
					put(grammarAccess.getFlowAccess().getFlowAlternatives_0(), "rule__Flow__FlowAlternatives_0");
					put(grammarAccess.getTYPEAccess().getTypeAlternatives_0(), "rule__TYPE__TypeAlternatives_0");
					put(grammarAccess.getRANGEAccess().getAlternatives(), "rule__RANGE__Alternatives");
					put(grammarAccess.getINTERVALAccess().getLsqbrAlternatives_0_0(), "rule__INTERVAL__LsqbrAlternatives_0_0");
					put(grammarAccess.getINTERVALAccess().getRsqbrAlternatives_4_0(), "rule__INTERVAL__RsqbrAlternatives_4_0");
					put(grammarAccess.getLiteralAccess().getAlternatives(), "rule__Literal__Alternatives");
					put(grammarAccess.getINSTRUCTIONAccess().getAlternatives(), "rule__INSTRUCTION__Alternatives");
					put(grammarAccess.getEQUAL_DIFFAccess().getOpAlternatives_1_1_0(), "rule__EQUAL_DIFF__OpAlternatives_1_1_0");
					put(grammarAccess.getCOMPARISONAccess().getOpAlternatives_1_1_0(), "rule__COMPARISON__OpAlternatives_1_1_0");
					put(grammarAccess.getADD_SUBAccess().getAlternatives_1_0(), "rule__ADD_SUB__Alternatives_1_0");
					put(grammarAccess.getMULT_DIVAccess().getAlternatives_1_0(), "rule__MULT_DIV__Alternatives_1_0");
					put(grammarAccess.getPrimaryExpressionAccess().getAlternatives(), "rule__PrimaryExpression__Alternatives");
					put(grammarAccess.getAtomicAccess().getAlternatives(), "rule__Atomic__Alternatives");
					put(grammarAccess.getMODULE_DECLAccess().getGroup(), "rule__MODULE_DECL__Group__0");
					put(grammarAccess.getCRITERION_DECLAccess().getGroup(), "rule__CRITERION_DECL__Group__0");
					put(grammarAccess.getDATASEL_DECLAccess().getGroup(), "rule__DATASEL_DECL__Group__0");
					put(grammarAccess.getDATASEL_DECLAccess().getGroup_5(), "rule__DATASEL_DECL__Group_5__0");
					put(grammarAccess.getVARAccess().getGroup(), "rule__VAR__Group__0");
					put(grammarAccess.getCSTAccess().getGroup(), "rule__CST__Group__0");
					put(grammarAccess.getINTERVALAccess().getGroup(), "rule__INTERVAL__Group__0");
					put(grammarAccess.getLSETAccess().getGroup(), "rule__LSET__Group__0");
					put(grammarAccess.getLSETAccess().getGroup_2(), "rule__LSET__Group_2__0");
					put(grammarAccess.getLiteralAccess().getGroup_0(), "rule__Literal__Group_0__0");
					put(grammarAccess.getLiteralAccess().getGroup_1(), "rule__Literal__Group_1__0");
					put(grammarAccess.getLiteralAccess().getGroup_2(), "rule__Literal__Group_2__0");
					put(grammarAccess.getLiteralAccess().getGroup_3(), "rule__Literal__Group_3__0");
					put(grammarAccess.getLiteralAccess().getGroup_4(), "rule__Literal__Group_4__0");
					put(grammarAccess.getLiteralAccess().getGroup_5(), "rule__Literal__Group_5__0");
					put(grammarAccess.getLiteralAccess().getGroup_6(), "rule__Literal__Group_6__0");
					put(grammarAccess.getLiteralAccess().getGroup_7(), "rule__Literal__Group_7__0");
					put(grammarAccess.getLiteralAccess().getGroup_8(), "rule__Literal__Group_8__0");
					put(grammarAccess.getIF_INSTRAccess().getGroup(), "rule__IF_INSTR__Group__0");
					put(grammarAccess.getIF_INSTRAccess().getGroup_7(), "rule__IF_INSTR__Group_7__0");
					put(grammarAccess.getLOOP_INSTRAccess().getGroup(), "rule__LOOP_INSTR__Group__0");
					put(grammarAccess.getERROR_INSTRAccess().getGroup(), "rule__ERROR_INSTR__Group__0");
					put(grammarAccess.getNULL_INSTRAccess().getGroup(), "rule__NULL_INSTR__Group__0");
					put(grammarAccess.getASSIGN_INSTRAccess().getGroup(), "rule__ASSIGN_INSTR__Group__0");
					put(grammarAccess.getASSIGN_INSTRAccess().getGroup_1(), "rule__ASSIGN_INSTR__Group_1__0");
					put(grammarAccess.getSINGLE_ASSIGNAccess().getGroup(), "rule__SINGLE_ASSIGN__Group__0");
					put(grammarAccess.getORAccess().getGroup(), "rule__OR__Group__0");
					put(grammarAccess.getORAccess().getGroup_1(), "rule__OR__Group_1__0");
					put(grammarAccess.getANDAccess().getGroup(), "rule__AND__Group__0");
					put(grammarAccess.getANDAccess().getGroup_1(), "rule__AND__Group_1__0");
					put(grammarAccess.getEQUAL_DIFFAccess().getGroup(), "rule__EQUAL_DIFF__Group__0");
					put(grammarAccess.getEQUAL_DIFFAccess().getGroup_1(), "rule__EQUAL_DIFF__Group_1__0");
					put(grammarAccess.getCOMPARISONAccess().getGroup(), "rule__COMPARISON__Group__0");
					put(grammarAccess.getCOMPARISONAccess().getGroup_1(), "rule__COMPARISON__Group_1__0");
					put(grammarAccess.getADD_SUBAccess().getGroup(), "rule__ADD_SUB__Group__0");
					put(grammarAccess.getADD_SUBAccess().getGroup_1(), "rule__ADD_SUB__Group_1__0");
					put(grammarAccess.getADD_SUBAccess().getGroup_1_0_0(), "rule__ADD_SUB__Group_1_0_0__0");
					put(grammarAccess.getADD_SUBAccess().getGroup_1_0_1(), "rule__ADD_SUB__Group_1_0_1__0");
					put(grammarAccess.getMULT_DIVAccess().getGroup(), "rule__MULT_DIV__Group__0");
					put(grammarAccess.getMULT_DIVAccess().getGroup_1(), "rule__MULT_DIV__Group_1__0");
					put(grammarAccess.getMULT_DIVAccess().getGroup_1_0_0(), "rule__MULT_DIV__Group_1_0_0__0");
					put(grammarAccess.getMULT_DIVAccess().getGroup_1_0_1(), "rule__MULT_DIV__Group_1_0_1__0");
					put(grammarAccess.getStrREDUCTIONAccess().getGroup(), "rule__StrREDUCTION__Group__0");
					put(grammarAccess.getStrREDUCTIONAccess().getGroup_1(), "rule__StrREDUCTION__Group_1__0");
					put(grammarAccess.getPrimaryExpressionAccess().getGroup_0(), "rule__PrimaryExpression__Group_0__0");
					put(grammarAccess.getPrimaryExpressionAccess().getGroup_1(), "rule__PrimaryExpression__Group_1__0");
					put(grammarAccess.getAtomicAccess().getGroup_0(), "rule__Atomic__Group_0__0");
					put(grammarAccess.getAtomicAccess().getGroup_1(), "rule__Atomic__Group_1__0");
					put(grammarAccess.getAtomicAccess().getGroup_2(), "rule__Atomic__Group_2__0");
					put(grammarAccess.getAtomicAccess().getGroup_3(), "rule__Atomic__Group_3__0");
					put(grammarAccess.getAtomicAccess().getGroup_4(), "rule__Atomic__Group_4__0");
					put(grammarAccess.getAtomicAccess().getGroup_5(), "rule__Atomic__Group_5__0");
					put(grammarAccess.getDECIMALAccess().getGroup(), "rule__DECIMAL__Group__0");
					put(grammarAccess.getDECIMALAccess().getGroup_2(), "rule__DECIMAL__Group_2__0");
					put(grammarAccess.getINTEGERAccess().getGroup(), "rule__INTEGER__Group__0");
					put(grammarAccess.getLANGUAGEAccess().getModulesAssignment(), "rule__LANGUAGE__ModulesAssignment");
					put(grammarAccess.getMODULE_DECLAccess().getNameAssignment_2(), "rule__MODULE_DECL__NameAssignment_2");
					put(grammarAccess.getMODULE_DECLAccess().getCritdeclAssignment_4(), "rule__MODULE_DECL__CritdeclAssignment_4");
					put(grammarAccess.getMODULE_DECLAccess().getDataseldeclAssignment_5(), "rule__MODULE_DECL__DataseldeclAssignment_5");
					put(grammarAccess.getMODULE_DECLAccess().getDeclarationAssignment_6(), "rule__MODULE_DECL__DeclarationAssignment_6");
					put(grammarAccess.getMODULE_DECLAccess().getInstrAssignment_7(), "rule__MODULE_DECL__InstrAssignment_7");
					put(grammarAccess.getCRITERION_DECLAccess().getCritAssignment_4(), "rule__CRITERION_DECL__CritAssignment_4");
					put(grammarAccess.getCRITERION_DECLAccess().getEndAssignment_5(), "rule__CRITERION_DECL__EndAssignment_5");
					put(grammarAccess.getDATASEL_DECLAccess().getData1Assignment_4(), "rule__DATASEL_DECL__Data1Assignment_4");
					put(grammarAccess.getDATASEL_DECLAccess().getData2Assignment_5_1(), "rule__DATASEL_DECL__Data2Assignment_5_1");
					put(grammarAccess.getDATASEL_DECLAccess().getEndAssignment_6(), "rule__DATASEL_DECL__EndAssignment_6");
					put(grammarAccess.getENDAccess().getEndAssignment(), "rule__END__EndAssignment");
					put(grammarAccess.getCRITERIONAccess().getCritAssignment(), "rule__CRITERION__CritAssignment");
					put(grammarAccess.getDATASELAccess().getSelAssignment(), "rule__DATASEL__SelAssignment");
					put(grammarAccess.getVARAccess().getFlowAssignment_1(), "rule__VAR__FlowAssignment_1");
					put(grammarAccess.getVARAccess().getNameAssignment_2(), "rule__VAR__NameAssignment_2");
					put(grammarAccess.getVARAccess().getTypeAssignment_4(), "rule__VAR__TypeAssignment_4");
					put(grammarAccess.getVARAccess().getRangeAssignment_5(), "rule__VAR__RangeAssignment_5");
					put(grammarAccess.getVARAccess().getEndAssignment_6(), "rule__VAR__EndAssignment_6");
					put(grammarAccess.getFlowAccess().getFlowAssignment(), "rule__Flow__FlowAssignment");
					put(grammarAccess.getCSTAccess().getFlowAssignment_1(), "rule__CST__FlowAssignment_1");
					put(grammarAccess.getCSTAccess().getNameAssignment_2(), "rule__CST__NameAssignment_2");
					put(grammarAccess.getCSTAccess().getTypeAssignment_4(), "rule__CST__TypeAssignment_4");
					put(grammarAccess.getCSTAccess().getValueAssignment_6(), "rule__CST__ValueAssignment_6");
					put(grammarAccess.getCSTAccess().getEndAssignment_8(), "rule__CST__EndAssignment_8");
					put(grammarAccess.getTYPEAccess().getTypeAssignment(), "rule__TYPE__TypeAssignment");
					put(grammarAccess.getINTERVALAccess().getLsqbrAssignment_0(), "rule__INTERVAL__LsqbrAssignment_0");
					put(grammarAccess.getINTERVALAccess().getMinAssignment_1(), "rule__INTERVAL__MinAssignment_1");
					put(grammarAccess.getINTERVALAccess().getMaxAssignment_3(), "rule__INTERVAL__MaxAssignment_3");
					put(grammarAccess.getINTERVALAccess().getRsqbrAssignment_4(), "rule__INTERVAL__RsqbrAssignment_4");
					put(grammarAccess.getLSETAccess().getValueAssignment_1(), "rule__LSET__ValueAssignment_1");
					put(grammarAccess.getLSETAccess().getValueAssignment_2_1(), "rule__LSET__ValueAssignment_2_1");
					put(grammarAccess.getLiteralAccess().getValueAssignment_0_1(), "rule__Literal__ValueAssignment_0_1");
					put(grammarAccess.getLiteralAccess().getValueAssignment_1_1(), "rule__Literal__ValueAssignment_1_1");
					put(grammarAccess.getLiteralAccess().getValueAssignment_2_1(), "rule__Literal__ValueAssignment_2_1");
					put(grammarAccess.getLiteralAccess().getValueAssignment_3_1(), "rule__Literal__ValueAssignment_3_1");
					put(grammarAccess.getLiteralAccess().getValueAssignment_4_1(), "rule__Literal__ValueAssignment_4_1");
					put(grammarAccess.getLiteralAccess().getValueAssignment_5_1(), "rule__Literal__ValueAssignment_5_1");
					put(grammarAccess.getLiteralAccess().getValueAssignment_6_1(), "rule__Literal__ValueAssignment_6_1");
					put(grammarAccess.getLiteralAccess().getValueAssignment_7_1(), "rule__Literal__ValueAssignment_7_1");
					put(grammarAccess.getLiteralAccess().getValueAssignment_8_1(), "rule__Literal__ValueAssignment_8_1");
					put(grammarAccess.getIF_INSTRAccess().getCondInstrAssignment_1(), "rule__IF_INSTR__CondInstrAssignment_1");
					put(grammarAccess.getIF_INSTRAccess().getIfstAssignment_5(), "rule__IF_INSTR__IfstAssignment_5");
					put(grammarAccess.getIF_INSTRAccess().getElstAssignment_7_3(), "rule__IF_INSTR__ElstAssignment_7_3");
					put(grammarAccess.getLOOP_INSTRAccess().getValAssignment_0(), "rule__LOOP_INSTR__ValAssignment_0");
					put(grammarAccess.getERROR_INSTRAccess().getEndAssignment_2(), "rule__ERROR_INSTR__EndAssignment_2");
					put(grammarAccess.getNULL_INSTRAccess().getEndAssignment_2(), "rule__NULL_INSTR__EndAssignment_2");
					put(grammarAccess.getASSIGN_INSTRAccess().getSaAssignment_0(), "rule__ASSIGN_INSTR__SaAssignment_0");
					put(grammarAccess.getASSIGN_INSTRAccess().getSaAssignment_1_1(), "rule__ASSIGN_INSTR__SaAssignment_1_1");
					put(grammarAccess.getASSIGN_INSTRAccess().getEndAssignment_2(), "rule__ASSIGN_INSTR__EndAssignment_2");
					put(grammarAccess.getSINGLE_ASSIGNAccess().getVarAssignment_0(), "rule__SINGLE_ASSIGN__VarAssignment_0");
					put(grammarAccess.getSINGLE_ASSIGNAccess().getExpAssignment_2(), "rule__SINGLE_ASSIGN__ExpAssignment_2");
					put(grammarAccess.getORAccess().getRightAssignment_1_2(), "rule__OR__RightAssignment_1_2");
					put(grammarAccess.getANDAccess().getRightAssignment_1_2(), "rule__AND__RightAssignment_1_2");
					put(grammarAccess.getEQUAL_DIFFAccess().getOpAssignment_1_1(), "rule__EQUAL_DIFF__OpAssignment_1_1");
					put(grammarAccess.getEQUAL_DIFFAccess().getRightAssignment_1_2(), "rule__EQUAL_DIFF__RightAssignment_1_2");
					put(grammarAccess.getCOMPARISONAccess().getOpAssignment_1_1(), "rule__COMPARISON__OpAssignment_1_1");
					put(grammarAccess.getCOMPARISONAccess().getRightAssignment_1_2(), "rule__COMPARISON__RightAssignment_1_2");
					put(grammarAccess.getADD_SUBAccess().getRightAssignment_1_1(), "rule__ADD_SUB__RightAssignment_1_1");
					put(grammarAccess.getMULT_DIVAccess().getRightAssignment_1_1(), "rule__MULT_DIV__RightAssignment_1_1");
					put(grammarAccess.getStrREDUCTIONAccess().getOpAssignment_1_1(), "rule__StrREDUCTION__OpAssignment_1_1");
					put(grammarAccess.getStrREDUCTIONAccess().getPosAssignment_1_3(), "rule__StrREDUCTION__PosAssignment_1_3");
					put(grammarAccess.getPrimaryExpressionAccess().getExpAssignment_1_2(), "rule__PrimaryExpression__ExpAssignment_1_2");
					put(grammarAccess.getAtomicAccess().getValueAssignment_0_1(), "rule__Atomic__ValueAssignment_0_1");
					put(grammarAccess.getAtomicAccess().getValueAssignment_1_1(), "rule__Atomic__ValueAssignment_1_1");
					put(grammarAccess.getAtomicAccess().getValueAssignment_2_1(), "rule__Atomic__ValueAssignment_2_1");
					put(grammarAccess.getAtomicAccess().getValueAssignment_3_1(), "rule__Atomic__ValueAssignment_3_1");
					put(grammarAccess.getAtomicAccess().getValueAssignment_4_1(), "rule__Atomic__ValueAssignment_4_1");
					put(grammarAccess.getAtomicAccess().getVrefAssignment_5_1(), "rule__Atomic__VrefAssignment_5_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.ui.contentassist.antlr.internal.InternalModuleDslParser typedParser = (org.xtext.ui.contentassist.antlr.internal.InternalModuleDslParser) parser;
			typedParser.entryRuleLANGUAGE();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public ModuleDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ModuleDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
