/*
* generated by Xtext
*/
package org.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ModuleDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.ui.internal.ModuleDslActivator.getInstance().getInjector("org.xtext.ModuleDsl");
	}
	
}
